Add switch case to router.hooks
savvy-coders/SPA-example-with-Axios pull request #11
Opened 2022-06-02 02:32 UTC by JohanBester

Hi Folks,

This PR is to add the SWITCH case statement to router.hooks

This PR needs to be merged to Development,
And then Development would need to be merged to master to get this change into the works before week 7

Kindly review and comment.
Thanks!

2022-06-02 13:15 UTC, matsinet requested changes

2022-06-02 13:15 UTC, matsinet commented on .gitignore
> +package-lock.json
The package-lock.json needs to be committed so remove that line

2022-06-02 13:15 UTC, matsinet commented on index.js
> +            `https://api.openweathermap.org/data/2.5/weather?appid=fbb30b5d6cf8e164ed522e5082b49064&q=st%20louis`
Replace the openweathermap key `fbb30b5d6cf8e164ed522e5082b49064` with the .env variable `${process.env.OPEN_WEATHER_MAP_API_KEY}`

2022-06-08 17:36 UTC, JohanBester commented on .gitignore
> +package-lock.json
Corrected this issue

2022-06-08 17:36 UTC, JohanBester commented on index.js
> +            `https://api.openweathermap.org/data/2.5/weather?appid=fbb30b5d6cf8e164ed522e5082b49064&q=st%20louis`
The API key has been replaced

2022-06-08 17:43 UTC, matsinet approved these changes

2022-06-08 17:48 UTC, merged