Replace 'state' with 'store'
savvy-coders/SPA-example-with-Axios pull request #5
Opened 2022-01-28 03:19 UTC by cbrantley4

2022-01-28 14:38 UTC, matsinet requested changes

2022-01-28 14:38 UTC, matsinet commented on components/Footer.js
> +// import * as store from "../store";
Go ahead and remove the comments as we don't normally put the weather in the footer
Besides that we should never import store directly into a view

2022-01-28 14:38 UTC, matsinet commented on index.js
> +      render(store.Home);
The `store.Home` can be removed now that we default it to that value in the render function i.e.:
`render();`

2022-01-28 15:22 UTC, matsinet approved these changes

2022-02-24 03:55 UTC, JohanBester approved these changes
I don't see any reason why not to merge this

2022-02-28 00:44 UTC, merged